### ISSUE TITLE
Country selection (Access): Support excluding certain countries

### ISSUE THREAD

**Issue by neufeind** [zeroseven/z7_countries#12]
Currently it's possible to use the "Country selection" (in Tab "Access") to select only certain countries to show this content for. Could we invert that, maybe with a checkbox or as a separate "mode" in the dropdown? That would allow showing it everywhere except in a certain country.

Usecase here is that we have a large list of countries (and regularly growing) but certain content should not show up in a certain country.
Or you might have one content-element to show "only in the US" and another to show "everywhere except the US" (without needing to check all other countries).

**Comment by raphaelthanner** [comment]
Hello, at the beginning of the implementation we wanted to implement this functionality. Unfortunately, this was not possible with the ExpressionBuilder in TYPO3.

If you find a good solution for this, we might be happy to tackle the topic again.
