### ISSUE TITLE
[FEATURE] Make delimiter and country/language-order configurable

### ISSUE THREAD

**Issue by neufeind** [zeroseven/z7_countries#3]
For LanguageManipulationService it would be nice to be able to override the base-delimiter as well as swap the order of country/language. This way you could also use "en/us" or "us/en" for the URLs. There are some sites that have the country first. If I see right having slash as the delimiter in the URLs shouldn't be a problem as well? hreflang is calculated separately (so should still be correct).

**Comment by neufeind** [comment]
Commit is a first attempt to resolve this. Of course the delimiter/order should better be configurable. But with this it can already at least easily be adjusted in the class.
Switched the delimiter-character for the preg-match to allow the delimiter to easily be set to '/'. This allows for example /en/us. And reversing the order (boolean) you can turn it into /us/en.

**Comment by raphaelthanner** [comment]
Hi @neufeind . Thank you very much. We wanted to stick to the pattern in the concept that is also used for the hreflang attribute, for example.
Therefore, there should initially be no additional configuration of the slug in the URL.
