### ISSUE TITLE
No access to country title in menu

### ISSUE THREAD

**Issue by abc-patricks** [zeroseven/z7_countries#5]
Hi,

I'm trying to set up a country/language menu. After some tries I managed to build the menu with via dataprocessing
`dataProcessing {
      10 = Zeroseven\Countries\DataProcessing\CountryMenuProcessor
      10 {
        as = countryMenu
      }
    }`

and in my FluidTemplate

`<f:for each="{countryMenu}" as="country">
            <f:if condition="{country.available}">
                    <div class="fw-bold">{country.object.properties.title}</div>
                    <f:for each="{country.languages}" as="language">
                        <f:if condition="{language.available}">
                                <a href="{language.link}" hreflang="{language.hreflang}">
                                    {language.object.title}
                                </a>
                        </f:if>
                    </f:for>
            </f:if>
        </f:for>`
        
The problem is that it won't show the country title as the properties in the country object are protected. Is there a way to access the properties?

**Comment by raphaelthanner** [comment]
Hi, there is a magic function inside the menu items (`Zeroseven\Countries\Menu\Item\AbstractItem`) that pass all `get`, `has`, and `is` calls to the `Country` or `SiteLanguage` object.

In php you can call `$countryMenuItem.getTitle()` in Fluid `{countryItem.data.title}`.

In your case try `<div class="fw-bold">{country.data.title}</div>`.

**Comment by abc-patricks** [comment]
Perfect! Works like a charm. 
Thanks for the quick response!
